name = "stargate-universe-client"
compatibility_date = "2025-01-01"

# Pages project configuration
[build]
command = "cd worker/client && npm run build"

[build.environment]
NODE_VERSION = "20"

[build.upload]
format = "service-worker"
dir = "worker/client/dist"
main = "./dist/assets/index-D64VDMd1.js"