extends RefCounted
class_name CharacterFactory

# Character generation system — the single source of truth for how every crew
# member looks in every context. Replaces character_style.gd.
#
# Three layers:
#   1. PROFILES   — who: base model + which outfit per context + military flag
#   2. OUTFITS    — what they wear: per-garment recolors + carried gear
#   3. SWATCH_GROUPS — how recolors land: Kenney mini-chars UV-map each garment
#      onto flat gradient swatches in the shared 512x512 colormap atlas, so
#      "change the shirt" = recolor that model's shirt cells in a per-instance
#      copy of the atlas. Faces/skin live in separate cells and never tint.
#
# Cell maps were generated by tools/probe_character_swatches.py (UV + vertex
# height analysis of each GLB) and are validated visually in the Character Lab
# (scenes/character_lab.tscn). Cells are Vector2i(col,row) on a 32px grid.
#
# Preload as a const Script and call statics — class_name lookup can lag in
# headless `-s` runs.

const COLORMAP_PATH: String = "res://models/characters/Textures/colormap.png"
const RIFLE_GLB: String = "res://models/gear/rifle.glb"
const ATLAS_CELL: int = 32

# --- snap points -----------------------------------------------------------
# Gear attaches to BONES via BoneAttachment3D, NOT to the body in body-space —
# so a helmet bobs with the head and a holstered pistol swings with the hips.
# The Kenney mini rig is shared by every roster model (7 bones: root, leg-left,
# leg-right, torso, arm-left, arm-right, head), so one mount table covers all.
#
# Each mount = a named snap point: which bone it rides + a local offset
# (position in skeleton-local units, euler rotation) tuned visually in the
# Character Lab. Offsets are small because they live under the model holder's
# 2.6x scale; gear meshes (authored in world units) are divided by that scale
# at attach time so they read at their intended real size.
# NOTE on signs: gear lives under the model holder's 180° Y-flip, so a +X/+Z
# offset here lands at world −X/−Z. The chunky mini torso is ~0.25 half-width,
# so offsets must push gear clear of the mesh. Tuned via gear_snap_debug.gd.
const MOUNTS: Dictionary = {
	# on the crown of the head bone
	"head":   {"bone": "head",      "pos": Vector3(0.0, 0.085, 0.0),   "rot": Vector3(0.0, 0.0, 0.0)},
	# slung diagonally high across the BACK (local +Z = world −Z = behind),
	# muzzle up over the shoulder
	"back":   {"bone": "torso",     "pos": Vector3(0.05, 0.26, 0.33),  "rot": Vector3(-1.30, 0.0, 0.55)},
	# holstered on the hip, clear of the body, barrel down
	"belt":   {"bone": "torso",     "pos": Vector3(0.30, -0.04, -0.05), "rot": Vector3(-1.57, 0.0, 0.0)},
	# in the right hand, presented forward (arm-right bone tip)
	"hand_r": {"bone": "arm-right", "pos": Vector3(0.0, -0.22, 0.04),  "rot": Vector3(0.0, 0.0, 0.0)},
	"hand_l": {"bone": "arm-left",  "pos": Vector3(0.0, -0.22, 0.04),  "rot": Vector3(0.0, 0.0, 0.0)},
}

# Where each gear kind rides by default (stowed) vs. when the character is
# aiming. Helmet has no aimed variant. Aiming also plays a holding-* animation
# (see AIM_ANIM) so the arm comes up to meet the hand-mounted weapon.
const GEAR_MOUNT: Dictionary = {"helmet": "head", "rifle": "back", "sidearm": "belt"}
const GEAR_MOUNT_AIMED: Dictionary = {"rifle": "hand_r", "sidearm": "hand_r"}
const GEAR_NODES: Array[String] = ["Helmet", "Rifle", "Sidearm"]

# Contexts a character can be dressed for. SHIP = aboard Destiny;
# MISSION = off-ship (planets, away missions).
const CTX_SHIP: String = "ship"
const CTX_MISSION: String = "mission"

# Uniform palette.
const COL_DUTY_TOP: Color = Color(0.16, 0.16, 0.19)      # ship duty blacks
const COL_DUTY_BOTTOM: Color = Color(0.12, 0.12, 0.145)
const COL_DUTY_BOOT: Color = Color(0.09, 0.09, 0.10)
const COL_FATIGUE_TOP: Color = Color(0.45, 0.50, 0.30)   # olive drab
const COL_FATIGUE_BOTTOM: Color = Color(0.36, 0.40, 0.24)
const COL_FATIGUE_BOOT: Color = Color(0.24, 0.20, 0.15)  # boot brown

# ---------------------------------------------------------------------------
# Layer 3: per-model garment -> atlas cells (from the UV probe).
# Optional "limbs" = bare-skin arm/leg cells that full uniforms also recolor
# (skin -> fabric reads as sleeves/trousers; hands read as gloves).
# ---------------------------------------------------------------------------
# Calibrated 2026-06-09 via tests/capture/swatch_calibrate.gd render-diff
# (probe heights alone mis-assigned hair/skin cells for several models —
# always re-calibrate after recasting a base model).
const SWATCH_GROUPS: Dictionary = {
	"eli": {
		# hair/face = col 1, skin = col 13, glasses = col 7 — never recolored.
		# (3,9)/(3,10): big low-vert shirt-front quads the probe's filter missed.
		"top": [Vector2i(3, 8), Vector2i(3, 9), Vector2i(3, 10), Vector2i(3, 11)],
		"bottom": [Vector2i(11, 9), Vector2i(11, 10), Vector2i(11, 12), Vector2i(11, 15)],
		"shoes": [Vector2i(5, 9), Vector2i(5, 10)],
	},
	"rush": {
		# hair/beard = (1,12)..(1,15), skin = col 11 — never recolored
		"top": [Vector2i(3, 8), Vector2i(3, 11)],
		"bottom": [Vector2i(15, 13), Vector2i(15, 14)],
		"shoes": [Vector2i(3, 13), Vector2i(3, 14)],
	},
	"scott": {
		# hair = (11,12)/(11,13), face = (11,14)/(11,15), arms skin = col 15.
		# accent = the red tie — stays red on duty blacks, goes olive on camo.
		"top": [Vector2i(1, 12), Vector2i(1, 15)],
		"bottom": [Vector2i(1, 13), Vector2i(1, 14)],
		"shoes": [],
		"accent": [Vector2i(9, 8), Vector2i(9, 9), Vector2i(9, 10), Vector2i(9, 11)],
	},
	"greer": {
		# base male-c is light-skinned; Greer's profile recolors the skin/hair
		# groups (profile-driven, not outfit-driven — see PROFILES).
		"top": [Vector2i(11, 8), Vector2i(11, 9), Vector2i(11, 10), Vector2i(1, 12), Vector2i(1, 14)],
		"bottom": [Vector2i(11, 11), Vector2i(1, 13)],
		"shoes": [Vector2i(3, 13), Vector2i(3, 14)],
		"skin": [Vector2i(11, 12), Vector2i(11, 14), Vector2i(11, 15), Vector2i(15, 12),
			Vector2i(15, 13), Vector2i(15, 14), Vector2i(15, 15)],
		"hair": [Vector2i(11, 13), Vector2i(1, 15)],
	},
	"young": {
		# hair = (13,12)/(13,13), face = (13,14)/(13,15) + col 15, glasses = col 7
		"top": [Vector2i(9, 12), Vector2i(9, 13), Vector2i(9, 14), Vector2i(9, 15), Vector2i(5, 8)],
		"bottom": [Vector2i(5, 9), Vector2i(5, 10), Vector2i(5, 11)],
		"shoes": [Vector2i(3, 13), Vector2i(3, 14)],
		"limbs": [Vector2i(1, 12), Vector2i(1, 13), Vector2i(1, 14), Vector2i(1, 15)],  # black cuffs
	},
	"park": {
		# hair = (1,12), face/arms = col 15 — never recolored
		"top": [Vector2i(1, 13), Vector2i(1, 14), Vector2i(1, 15), Vector2i(9, 12), Vector2i(11, 8)],
		"bottom": [Vector2i(9, 13), Vector2i(9, 14), Vector2i(9, 15), Vector2i(11, 11)],
		"shoes": [Vector2i(7, 13), Vector2i(7, 14), Vector2i(7, 15)],
	},
	"james": {
		# hair = col 3 (incl. bangs at face height), skin = col 11 rows 12-15
		"top": [Vector2i(11, 8)],
		"bottom": [Vector2i(9, 8), Vector2i(9, 11), Vector2i(9, 14), Vector2i(11, 11)],
		"shoes": [Vector2i(15, 13), Vector2i(15, 14)],
	},
	"lt_james": {
		# hair = (1,12)..(1,15), skin = col 13 — never recolored.
		# (15,9)/(15,10): big low-vert chest quads the probe's filter missed.
		"top": [Vector2i(11, 8), Vector2i(15, 8), Vector2i(15, 9), Vector2i(15, 10), Vector2i(15, 11)],
		"bottom": [Vector2i(11, 9), Vector2i(11, 10), Vector2i(11, 11), Vector2i(11, 12), Vector2i(11, 15)],
		"shoes": [Vector2i(15, 13), Vector2i(15, 14), Vector2i(9, 13), Vector2i(9, 14)],
	},
	"chloe": {
		# hair = (11,12)/(11,13), face = (11,14)/(11,15), arms = col 15 rows 12-15
		"top": [Vector2i(5, 8), Vector2i(5, 11)],
		"bottom": [Vector2i(15, 9), Vector2i(15, 10), Vector2i(15, 8), Vector2i(15, 11), Vector2i(1, 13), Vector2i(1, 14)],
		"shoes": [Vector2i(9, 13), Vector2i(9, 14)],
	},
}

# ---------------------------------------------------------------------------
# Layer 2: outfits — garment recolors + gear loadout.
# An empty recolor dict means "wear the base model's own colors".
# ---------------------------------------------------------------------------
const OUTFITS: Dictionary = {
	"civvies": {"recolor": {}, "gear": []},
	"fatigues": {
		"recolor": {
			"top": COL_FATIGUE_TOP, "bottom": COL_FATIGUE_BOTTOM,
			"shoes": COL_FATIGUE_BOOT, "limbs": COL_FATIGUE_TOP,
			"accent": COL_FATIGUE_BOTTOM,
		},
		"gear": [],
	},
	"duty_black": {
		"recolor": {
			"top": COL_DUTY_TOP, "bottom": COL_DUTY_BOTTOM,
			"shoes": COL_DUTY_BOOT, "limbs": COL_DUTY_TOP,
		},
		"gear": ["sidearm"],
	},
	"combat": {
		"recolor": {
			"top": COL_FATIGUE_TOP, "bottom": COL_FATIGUE_BOTTOM,
			"shoes": COL_FATIGUE_BOOT, "limbs": COL_FATIGUE_TOP,
			"accent": COL_FATIGUE_BOTTOM,
		},
		"gear": ["sidearm", "rifle"],
	},
}

# ---------------------------------------------------------------------------
# Layer 1: who wears what where. Military crew: blacks + sidearm on the ship,
# camo + rifle + sidearm off-ship. Civilians: their own clothes on the ship,
# unarmed fatigues on missions.
# ---------------------------------------------------------------------------
# The PRIMARY in-game body is the Quaternius ModularCharacter ("mod" key:
# gender + hairstyle; outfits resolve from the ship/mission outfit ids via
# MODULAR_LOADOUTS). "vrm" = secondary VRoid body (expressions); "model" =
# legacy mini fallback. Current outfit parts are the fantasy placeholders
# (Peasant=civvies, Ranger=uniform) until SGU outfits are authored on the rig.
const PROFILES: Dictionary = {
	"Eli": {"model": "eli", "vrm": "res://models/vrm/eli.vrm", "ship": "civvies", "mission": "fatigues", "military": false,
		"mod": {"gender": "Male", "hair": "Hair_SimpleParted", "hair_color": Color(0.28, 0.18, 0.10)}},
	"Dr Rush": {"model": "rush", "ship": "civvies", "mission": "fatigues", "military": false,
		"mod": {"gender": "Male", "hair": "Hair_Beard", "hair_color": Color(0.30, 0.24, 0.18)}},
	"Dr Park": {"model": "park", "ship": "civvies", "mission": "fatigues", "military": false,
		"mod": {"gender": "Female", "hair": "Hair_Buns", "hair_color": Color(0.08, 0.07, 0.07)}},
	"Dr James": {"model": "james", "ship": "civvies", "mission": "fatigues", "military": false,
		"mod": {"gender": "Female", "hair": "Hair_Long", "hair_color": Color(0.42, 0.27, 0.14)}},
	"Chloe Armstrong": {"model": "chloe", "ship": "civvies", "mission": "fatigues", "military": false,
		"mod": {"gender": "Female", "hair": "Hair_Long", "hair_color": Color(0.45, 0.32, 0.16)}},
	"Lt Scott": {"model": "scott", "vrm": "res://models/vrm/scott.vrm", "ship": "duty_black", "mission": "combat", "military": true,
		"mod": {"gender": "Male", "hair": "Hair_Buzzed", "hair_color": Color(0.24, 0.16, 0.09)}},
	# Greer's skin/hair recolors bake into every outfit (the old away-team
	# hack tinted Scott's whole body brown; this is the parameterized version).
	"Sgt Greer": {
		"model": "greer", "ship": "duty_black", "mission": "combat", "military": true,
		"skin": Color(0.46, 0.28, 0.18), "hair": Color(0.10, 0.09, 0.08),
		"mod": {"gender": "Male", "hair": "Hair_Buzzed", "skin": "Dark", "hair_color": Color(0.05, 0.05, 0.05)},
	},
	"Colonel Young": {"model": "young", "ship": "duty_black", "mission": "combat", "military": true,
		"mod": {"gender": "Male", "hair": "Hair_Buzzed", "hair_color": Color(0.35, 0.30, 0.26)}},
	"Lt James": {"model": "lt_james", "ship": "duty_black", "mission": "combat", "military": true,
		"mod": {"gender": "Female", "hair": "Hair_BuzzedFemale", "hair_color": Color(0.10, 0.08, 0.07)}},
}

# Modular outfit loadouts per mini-outfit id: which Quaternius outfit family
# dresses each context, the clothing tint (ship duty = blacks; field = the
# parts' natural colors standing in for camo), and carried gear.
const MODULAR_LOADOUTS: Dictionary = {
	"civvies": {"outfit": "Peasant", "tint": Color.WHITE, "sidearm": false, "rifle": false},
	"fatigues": {"outfit": "Peasant", "tint": Color(0.55, 0.58, 0.42), "sidearm": false, "rifle": false},
	"duty_black": {"outfit": "Ranger", "tint": Color(0.30, 0.30, 0.34), "sidearm": true, "rifle": false},
	"combat": {"outfit": "Ranger", "tint": Color.WHITE, "sidearm": true, "rifle": true},
}

# Baked outfit textures, keyed "model|outfit". Characters sharing a look share
# one texture; recolors never touch the base colormap resource itself.
static var _texture_cache: Dictionary = {}


# --------------------------- profile resolution ----------------------------

static func profile_for(character_name: String) -> Dictionary:
	if PROFILES.has(character_name):
		return PROFILES[character_name]
	if ALIASES.has(character_name):
		return PROFILES[ALIASES[character_name]]
	# Generic spawn labels ("Soldier 2") fall back by keyword.
	if is_military(character_name):
		return {"model": "scott", "ship": "duty_black", "mission": "combat", "military": true}
	return {"model": "", "ship": "civvies", "mission": "fatigues", "military": false}


# Label variants resolve to the canonical profile so "Greer" (planet away
# team) and "Sgt Greer" (ship) are the same person.
const ALIASES: Dictionary = {
	"Greer": "Sgt Greer", "Scott": "Lt Scott", "Young": "Colonel Young",
	"Rush": "Dr Rush", "Park": "Dr Park", "Chloe": "Chloe Armstrong",
}


# Exact profile flag first; keyword fallback keeps every label variant a spawn
# site might use working ("Greer", "Soldier 2"). NOTE: "Dr James" is a civilian
# while "Lt James" is military — keyword matching alone can't tell them apart,
# which is why the profile flag wins.
static func is_military(character_name: String) -> bool:
	if PROFILES.has(character_name):
		return bool(PROFILES[character_name]["military"])
	return character_name.contains("Greer") \
		or character_name.contains("Scott") \
		or character_name.contains("Soldier")


# Resolve a character's base model path, falling back to a per-site default
# for characters not in the registry.
static func model_for(character_name: String, fallback: String = "") -> String:
	var stem: String = String(profile_for(character_name)["model"])
	if stem == "":
		return fallback
	return "res://models/characters/%s.glb" % stem


static func outfit_id_for(character_name: String, context: String) -> String:
	var profile: Dictionary = profile_for(character_name)
	return String(profile.get(context, "civvies"))


# --------------------------- modular crew bodies ----------------------------

# Preloaded lazily to avoid a load-order cycle (modular_character preloads us
# back for the gear builders).
static var _modular_script: Script = null


static func _modular() -> Script:
	if _modular_script == null:
		_modular_script = load("res://scripts/modular_character.gd")
	return _modular_script


# Build the PRIMARY in-game body for a character: a ModularCharacter with the
# profile's gender/hair. Call dress_modular AFTER adding it to the tree (slot
# equipment needs the skeleton, which exists post-_ready).
static func build_modular(character_name: String) -> Node3D:
	var mod: Dictionary = profile_for(character_name).get("mod", {"gender": "Male", "hair": ""})
	var c: Node3D = _modular().call("create", String(mod.get("gender", "Male")))
	c.name = "Mod_" + character_name.replace(" ", "")
	return c


# Outfit + gear for a context, resolved through the same outfit ids as the
# mini pipeline (civvies / fatigues / duty_black / combat).
static func dress_modular(c: Node3D, character_name: String, context: String = CTX_SHIP) -> void:
	var profile: Dictionary = profile_for(character_name)
	var mod: Dictionary = profile.get("mod", {})
	var outfit_id: String = outfit_id_for(character_name, context)
	var loadout: Dictionary = MODULAR_LOADOUTS.get(outfit_id, MODULAR_LOADOUTS["civvies"])
	var gender: String = String(mod.get("gender", "Male"))
	for slot in ["Body", "Arms", "Legs", "Feet"]:
		c.call("set_slot", slot, _modular_part(slot, gender, String(loadout["outfit"])))
	if String(mod.get("hair", "")) != "":
		c.call("set_slot", "Hair", String(mod["hair"]))
		c.call("set_hair_color", mod.get("hair_color", Color(0.32, 0.22, 0.14)))
	var tint: Color = loadout["tint"]
	if tint != Color.WHITE:
		c.call("tint_clothing", tint)
	if String(mod.get("skin", "")) != "":
		c.call("set_skin_variant", String(mod["skin"]))
	c.call("set_sidearm", bool(loadout["sidearm"]), false)
	c.call("set_rifle", bool(loadout["rifle"]), false)


# Resolve a slot's part stem for an outfit family, tolerant of the pack's
# naming variance (Male_Ranger_Feet_Boots vs Female_Ranger_Feet).
static func _modular_part(slot: String, gender: String, outfit: String) -> String:
	for stem in _modular().call("parts_for_slot", slot, gender):
		if String(stem).contains("_" + outfit + "_"):
			return String(stem)
	return ""


# ------------------------------- dressing ----------------------------------

# Dress a spawned character for a context: bake/apply the outfit texture onto
# the model and snap carried gear onto the SKELETON's bones. `model_root` is the
# Model holder wrapping the GLB instance (the skeleton is found inside it).
# `model_scale` is the holder's uniform scale — gear meshes are authored in
# world units and divided by it so they read at the right size on the rig.
# `aimed` routes weapons to the hand mount instead of back/belt.
# `body` is accepted for call-site compatibility (gear no longer lives there).
static func dress(body: Node3D, model_root: Node, character_name: String, context: String = CTX_SHIP, model_scale: float = 2.6, aimed: bool = false) -> void:
	var outfit_id: String = outfit_id_for(character_name, context)
	apply_texture(model_root, character_texture(character_name, context))
	var outfit: Dictionary = OUTFITS.get(outfit_id, OUTFITS["civvies"])
	var skel: Skeleton3D = _find_skeleton(model_root)
	if skel != null:
		_sync_gear(skel, outfit["gear"], model_scale, aimed)


# Walk the model and override every mesh with a material using `tex` — same
# idiom as Npc.apply_kenney_colormap (Godot drops the GLB's external texture
# binding on import; without this minis render solid white).
static func apply_texture(model_root: Node, tex: Texture2D) -> void:
	if model_root == null or tex == null:
		return
	var mat: StandardMaterial3D = StandardMaterial3D.new()
	mat.albedo_texture = tex
	mat.roughness = 0.78
	mat.metallic = 0.0
	var stack: Array = [model_root]
	while not stack.is_empty():
		var n: Node = stack.pop_back()
		if n is MeshInstance3D:
			(n as MeshInstance3D).material_override = mat
		for c in n.get_children():
			stack.append(c)


# ----------------------------- outfit baking -------------------------------

# The texture a specific character wears in a context: the outfit's recolors
# plus the profile's identity overrides (skin/hair) baked together. Greer's
# skin tone follows him into every outfit this way.
static func character_texture(character_name: String, context: String) -> Texture2D:
	var profile: Dictionary = profile_for(character_name)
	var stem: String = String(profile["model"])
	var outfit_id: String = outfit_id_for(character_name, context)
	if not (profile.has("skin") or profile.has("hair")):
		return outfit_texture(stem, outfit_id)
	var key: String = "%s|%s|%s" % [character_name, stem, outfit_id]
	if _texture_cache.has(key):
		return _texture_cache[key]
	var outfit: Dictionary = OUTFITS.get(outfit_id, OUTFITS["civvies"])
	var recolor: Dictionary = (outfit["recolor"] as Dictionary).duplicate()
	if profile.has("skin"):
		recolor["skin"] = profile["skin"]
	if profile.has("hair"):
		recolor["hair"] = profile["hair"]
	var baked: Texture2D = custom_texture(stem, recolor)
	_texture_cache[key] = baked
	return baked

# Bake (and cache) the colormap variant for a model+outfit. Civvies and
# unknown models return the base atlas untouched.
static func outfit_texture(model_stem: String, outfit_id: String) -> Texture2D:
	var key: String = "%s|%s" % [model_stem, outfit_id]
	if _texture_cache.has(key):
		return _texture_cache[key]
	var outfit: Dictionary = OUTFITS.get(outfit_id, OUTFITS["civvies"])
	var baked: Texture2D = custom_texture(model_stem, outfit["recolor"])
	_texture_cache[key] = baked
	return baked


# Uncached bake with an arbitrary recolor dict (role -> Color) — the Character
# Lab's live-tweak path. Promote a good result into OUTFITS to ship it.
static func custom_texture(model_stem: String, recolor: Dictionary) -> Texture2D:
	var base: Texture2D = load(COLORMAP_PATH)
	var groups: Dictionary = SWATCH_GROUPS.get(model_stem, {})
	if recolor.is_empty() or groups.is_empty():
		return base
	var img: Image = base.get_image()
	if img.is_compressed():
		img.decompress()
	img.convert(Image.FORMAT_RGBA8)
	for role in recolor:
		var target: Color = recolor[role]
		for cell in groups.get(role, []):
			_recolor_cell(img, cell, target)
	return ImageTexture.create_from_image(img)


# Luminance-preserving recolor of one 32px atlas cell: the swatch keeps its
# vertical gradient (Kenney's baked-in shading) but shifts to the target hue.
static func _recolor_cell(img: Image, cell: Vector2i, target: Color) -> void:
	var x0: int = cell.x * ATLAS_CELL
	var y0: int = cell.y * ATLAS_CELL
	if x0 < 0 or y0 < 0 or x0 + ATLAS_CELL > img.get_width() or y0 + ATLAS_CELL > img.get_height():
		return
	var mean_luma: float = 0.0
	for y in range(y0, y0 + ATLAS_CELL):
		for x in range(x0, x0 + ATLAS_CELL):
			var c: Color = img.get_pixel(x, y)
			mean_luma += (c.r + c.g + c.b) / 3.0
	mean_luma = maxf(mean_luma / float(ATLAS_CELL * ATLAS_CELL), 0.001)
	for y in range(y0, y0 + ATLAS_CELL):
		for x in range(x0, x0 + ATLAS_CELL):
			var c: Color = img.get_pixel(x, y)
			var f: float = ((c.r + c.g + c.b) / 3.0) / mean_luma
			img.set_pixel(x, y, Color(
				clampf(target.r * f, 0.0, 1.0),
				clampf(target.g * f, 0.0, 1.0),
				clampf(target.b * f, 0.0, 1.0),
				c.a))


# -------------------------------- gear -------------------------------------
# Gear rides BoneAttachment3D nodes on the skeleton (real snap points), so it
# tracks animation. The hierarchy under the model holder ends up:
#   Skeleton3D
#     body-mesh / head-mesh
#     Mount_head   (BoneAttachment3D bone=head)  -> Helmet
#     Mount_torso  (BoneAttachment3D bone=torso) -> Rifle (slung) / Sidearm (hip)
#     Mount_arm-right (...)                       -> weapon when aimed

# Find the Skeleton3D the importer creates inside the GLB (one level deep,
# not at the holder root — same reasoning as the AnimationPlayer lookup).
static func _find_skeleton(model_root: Node) -> Skeleton3D:
	if model_root == null:
		return null
	var stack: Array = [model_root]
	while not stack.is_empty():
		var n: Node = stack.pop_back()
		if n is Skeleton3D:
			return n
		for c in n.get_children():
			stack.append(c)
	return null


# Sync the skeleton's snapped gear to the loadout: drop gear no longer carried,
# (re)attach what is, at the mount appropriate for the aim state. When aiming,
# only ONE weapon goes to the hand (rifle wins); the rest stay stowed.
static func _sync_gear(skel: Skeleton3D, loadout: Array, model_scale: float, aimed: bool) -> void:
	for node_name in GEAR_NODES:
		if not loadout.has(node_name.to_lower()):
			_remove_gear(skel, node_name)
	var primary: String = aimed_weapon(loadout) if aimed else ""
	for gear_id in loadout:
		attach_gear(skel, gear_id, model_scale, gear_id == primary)


# Which weapon a loadout presents when aiming (rifle over sidearm).
static func aimed_weapon(loadout: Array) -> String:
	if loadout.has("rifle"):
		return "rifle"
	if loadout.has("sidearm"):
		return "sidearm"
	return ""


# Detach a gear kind from wherever it is on the skeleton.
static func _remove_gear(skel: Skeleton3D, node_name: String) -> void:
	for ba in skel.get_children():
		if not (ba is BoneAttachment3D):
			continue
		var g: Node = ba.get_node_or_null(node_name)
		if g != null:
			g.name = node_name + "_retired"
			g.queue_free()


# Attach a gear kind to its mount (aim-aware), idempotently. Returns the gear
# node. `body`-free: everything hangs off the skeleton so it follows the rig.
static func attach_gear(skel: Skeleton3D, gear_id: String, model_scale: float = 2.6, aimed: bool = false) -> Node3D:
	if skel == null:
		return null
	var node_name: String = gear_id.capitalize()
	var mount_name: String = ""
	if aimed and GEAR_MOUNT_AIMED.has(gear_id):
		mount_name = GEAR_MOUNT_AIMED[gear_id]
	else:
		mount_name = GEAR_MOUNT.get(gear_id, "head")
	var mount: Dictionary = MOUNTS.get(mount_name, MOUNTS["head"])

	# Already attached at the correct mount? leave it. Otherwise detach + rebuild.
	var attach: BoneAttachment3D = _bone_attachment(skel, String(mount["bone"]))
	var existing: Node = attach.get_node_or_null(node_name)
	if existing != null:
		return existing as Node3D
	_remove_gear(skel, node_name)   # might be on a different bone

	var gear: Node3D = null
	match gear_id:
		"sidearm": gear = build_sidearm()
		"rifle":   gear = build_rifle()
		"helmet":  gear = build_helmet()
	if gear == null:
		return null
	gear.name = node_name
	# Place at the snap offset; divide by model scale so the world-unit mesh
	# reads correctly under the holder's uniform scale.
	gear.position = (mount["pos"] as Vector3) / model_scale
	gear.rotation = mount["rot"]
	gear.scale = Vector3.ONE / model_scale
	attach.add_child(gear)
	return gear


# One BoneAttachment3D per bone, cached as a named child of the skeleton so
# multiple gear pieces can share a bone (rifle on back + sidearm on hip both
# ride `torso`).
static func _bone_attachment(skel: Skeleton3D, bone_name: String) -> BoneAttachment3D:
	var attach_name: String = "Mount_" + bone_name
	var existing: Node = skel.get_node_or_null(attach_name)
	if existing is BoneAttachment3D:
		return existing
	var ba: BoneAttachment3D = BoneAttachment3D.new()
	ba.name = attach_name
	skel.add_child(ba)
	ba.bone_name = bone_name   # set AFTER entering the tree so it resolves
	return ba


# Dark-olive combat helmet — a squashed dome, origin at the skull base so the
# head mount lifts it onto the crown. World-unit sized.
static func build_helmet() -> MeshInstance3D:
	var helmet: MeshInstance3D = MeshInstance3D.new()
	helmet.name = "Helmet"
	var dome: SphereMesh = SphereMesh.new()
	dome.radius = 0.30
	dome.height = 0.40
	dome.is_hemisphere = true
	helmet.mesh = dome
	var mat: StandardMaterial3D = StandardMaterial3D.new()
	mat.albedo_color = Color(0.20, 0.24, 0.16)
	mat.roughness = 0.7
	mat.metallic = 0.0
	helmet.material_override = mat
	return helmet


# Procedural sidearm in canonical gear frame: barrel along -Z, grip down,
# origin at the grip/trigger (where the hand holds it and where it clips to a
# holster). The MOUNT rotation decides holstered-on-hip vs presented-in-hand.
static func build_sidearm() -> Node3D:
	var pivot: Node3D = Node3D.new()
	pivot.name = "Sidearm"
	var mat: StandardMaterial3D = StandardMaterial3D.new()
	mat.albedo_color = Color(0.05, 0.05, 0.06)
	mat.metallic = 0.6
	mat.roughness = 0.45
	var slide: MeshInstance3D = MeshInstance3D.new()
	var smesh: BoxMesh = BoxMesh.new()
	smesh.size = Vector3(0.11, 0.14, 0.54)
	slide.mesh = smesh
	slide.material_override = mat
	slide.position = Vector3(0.0, 0.0, -0.22)
	pivot.add_child(slide)
	var grip: MeshInstance3D = MeshInstance3D.new()
	var gmesh: BoxMesh = BoxMesh.new()
	gmesh.size = Vector3(0.08, 0.24, 0.11)
	grip.mesh = gmesh
	grip.material_override = mat
	grip.position = Vector3(0.0, -0.16, 0.06)
	pivot.add_child(grip)
	return pivot


# Kenney Blaster Kit rifle (blaster-e) in canonical gear frame: barrel along
# -Z, grip near the origin. The MOUNT decides slung-on-back vs in-hand.
# Auto-scaled so the longest axis spans ~0.85 world units.
static func build_rifle() -> Node3D:
	var pivot: Node3D = Node3D.new()
	pivot.name = "Rifle"
	var glb: PackedScene = load(RIFLE_GLB)
	if glb == null:
		return pivot
	var inst: Node3D = glb.instantiate()
	var aabb: AABB = _merged_aabb(inst)
	var longest: float = maxf(aabb.size.x, maxf(aabb.size.y, aabb.size.z))
	if longest > 0.001:
		inst.scale = Vector3.ONE * (0.85 / longest)
	# Kenney blasters model the barrel along +Z; flip to -Z (gear forward).
	if aabb.size.z >= aabb.size.x and aabb.size.z >= aabb.size.y:
		inst.rotation.y = PI
	else:
		inst.rotation.y = PI * 0.5
	# Center the mesh on the pivot (grip ≈ centre for a rifle).
	inst.position = -(aabb.get_center() * inst.scale).rotated(Vector3.UP, inst.rotation.y)
	var mat: StandardMaterial3D = StandardMaterial3D.new()
	mat.albedo_color = Color(0.24, 0.25, 0.28)
	mat.metallic = 0.45
	mat.roughness = 0.45
	var stack: Array = [inst]
	while not stack.is_empty():
		var n: Node = stack.pop_back()
		if n is MeshInstance3D:
			(n as MeshInstance3D).material_override = mat
		for c in n.get_children():
			stack.append(c)
	pivot.add_child(inst)
	return pivot


# Transform-aware merged AABB in `root`'s local frame. MeshInstance3D.get_aabb()
# alone is mesh-local and misses inner node scales (Kenney blasters nest a
# scaled node inside the GLB), which made the rifle measure 3x its true size.
static func _merged_aabb(root: Node) -> AABB:
	var merged: AABB = AABB()
	var first: bool = true
	if root is MeshInstance3D:
		merged = (root as MeshInstance3D).get_aabb()
		first = false
	for c in root.get_children():
		var out: Array = _aabb_walk(c, Transform3D.IDENTITY, merged, first)
		first = out[0]
		merged = out[1]
	return merged


static func _aabb_walk(node: Node, xf: Transform3D, merged: AABB, first: bool) -> Array:
	var local_xf: Transform3D = xf
	if node is Node3D:
		local_xf = xf * (node as Node3D).transform
	if node is MeshInstance3D:
		var box: AABB = local_xf * (node as MeshInstance3D).get_aabb()
		if first:
			merged = box
			first = false
		else:
			merged = merged.merge(box)
	for c in node.get_children():
		var out: Array = _aabb_walk(c, local_xf, merged, first)
		merged = out[1]
		first = out[0]
	return [first, merged]
