extends RefCounted
class_name CharacterFactory

# Character generation system — the single source of truth for how every crew
# member looks in every context. Replaces character_style.gd.
#
# Three layers:
#   1. PROFILES   — who: base model + which outfit per context + military flag
#   2. OUTFITS    — what they wear: per-garment recolors + carried gear
#   3. SWATCH_GROUPS — how recolors land: Kenney mini-chars UV-map each garment
#      onto flat gradient swatches in the shared 512x512 colormap atlas, so
#      "change the shirt" = recolor that model's shirt cells in a per-instance
#      copy of the atlas. Faces/skin live in separate cells and never tint.
#
# Cell maps were generated by tools/probe_character_swatches.py (UV + vertex
# height analysis of each GLB) and are validated visually in the Character Lab
# (scenes/character_lab.tscn). Cells are Vector2i(col,row) on a 32px grid.
#
# Preload as a const Script and call statics — class_name lookup can lag in
# headless `-s` runs.

const COLORMAP_PATH: String = "res://models/characters/Textures/colormap.png"
const RIFLE_GLB: String = "res://models/gear/rifle.glb"
const ATLAS_CELL: int = 32

# Contexts a character can be dressed for. SHIP = aboard Destiny;
# MISSION = off-ship (planets, away missions).
const CTX_SHIP: String = "ship"
const CTX_MISSION: String = "mission"

# Uniform palette.
const COL_DUTY_TOP: Color = Color(0.16, 0.16, 0.19)      # ship duty blacks
const COL_DUTY_BOTTOM: Color = Color(0.12, 0.12, 0.145)
const COL_DUTY_BOOT: Color = Color(0.09, 0.09, 0.10)
const COL_FATIGUE_TOP: Color = Color(0.45, 0.50, 0.30)   # olive drab
const COL_FATIGUE_BOTTOM: Color = Color(0.36, 0.40, 0.24)
const COL_FATIGUE_BOOT: Color = Color(0.24, 0.20, 0.15)  # boot brown

# ---------------------------------------------------------------------------
# Layer 3: per-model garment -> atlas cells (from the UV probe).
# Optional "limbs" = bare-skin arm/leg cells that full uniforms also recolor
# (skin -> fabric reads as sleeves/trousers; hands read as gloves).
# ---------------------------------------------------------------------------
# Calibrated 2026-06-09 via tests/capture/swatch_calibrate.gd render-diff
# (probe heights alone mis-assigned hair/skin cells for several models —
# always re-calibrate after recasting a base model).
const SWATCH_GROUPS: Dictionary = {
	"eli": {
		# hair/face = col 1, skin = col 13, glasses = col 7 — never recolored.
		# (3,9)/(3,10): big low-vert shirt-front quads the probe's filter missed.
		"top": [Vector2i(3, 8), Vector2i(3, 9), Vector2i(3, 10), Vector2i(3, 11)],
		"bottom": [Vector2i(11, 9), Vector2i(11, 10), Vector2i(11, 12), Vector2i(11, 15)],
		"shoes": [Vector2i(5, 9), Vector2i(5, 10)],
	},
	"rush": {
		# hair/beard = (1,12)..(1,15), skin = col 11 — never recolored
		"top": [Vector2i(3, 8), Vector2i(3, 11)],
		"bottom": [Vector2i(15, 13), Vector2i(15, 14)],
		"shoes": [Vector2i(3, 13), Vector2i(3, 14)],
	},
	"scott": {
		# hair = (11,12)/(11,13), face = (11,14)/(11,15), arms skin = col 15.
		# accent = the red tie — stays red on duty blacks, goes olive on camo.
		"top": [Vector2i(1, 12), Vector2i(1, 15)],
		"bottom": [Vector2i(1, 13), Vector2i(1, 14)],
		"shoes": [],
		"accent": [Vector2i(9, 8), Vector2i(9, 9), Vector2i(9, 10), Vector2i(9, 11)],
	},
	"greer": {
		# base male-c is light-skinned; Greer's profile recolors the skin/hair
		# groups (profile-driven, not outfit-driven — see PROFILES).
		"top": [Vector2i(11, 8), Vector2i(11, 9), Vector2i(11, 10), Vector2i(1, 12), Vector2i(1, 14)],
		"bottom": [Vector2i(11, 11), Vector2i(1, 13)],
		"shoes": [Vector2i(3, 13), Vector2i(3, 14)],
		"skin": [Vector2i(11, 12), Vector2i(11, 14), Vector2i(11, 15), Vector2i(15, 12),
			Vector2i(15, 13), Vector2i(15, 14), Vector2i(15, 15)],
		"hair": [Vector2i(11, 13), Vector2i(1, 15)],
	},
	"young": {
		# hair = (13,12)/(13,13), face = (13,14)/(13,15) + col 15, glasses = col 7
		"top": [Vector2i(9, 12), Vector2i(9, 13), Vector2i(9, 14), Vector2i(9, 15), Vector2i(5, 8)],
		"bottom": [Vector2i(5, 9), Vector2i(5, 10), Vector2i(5, 11)],
		"shoes": [Vector2i(3, 13), Vector2i(3, 14)],
		"limbs": [Vector2i(1, 12), Vector2i(1, 13), Vector2i(1, 14), Vector2i(1, 15)],  # black cuffs
	},
	"park": {
		# hair = (1,12), face/arms = col 15 — never recolored
		"top": [Vector2i(1, 13), Vector2i(1, 14), Vector2i(1, 15), Vector2i(9, 12), Vector2i(11, 8)],
		"bottom": [Vector2i(9, 13), Vector2i(9, 14), Vector2i(9, 15), Vector2i(11, 11)],
		"shoes": [Vector2i(7, 13), Vector2i(7, 14), Vector2i(7, 15)],
	},
	"james": {
		# hair = col 3 (incl. bangs at face height), skin = col 11 rows 12-15
		"top": [Vector2i(11, 8)],
		"bottom": [Vector2i(9, 8), Vector2i(9, 11), Vector2i(9, 14), Vector2i(11, 11)],
		"shoes": [Vector2i(15, 13), Vector2i(15, 14)],
	},
	"lt_james": {
		# hair = (1,12)..(1,15), skin = col 13 — never recolored.
		# (15,9)/(15,10): big low-vert chest quads the probe's filter missed.
		"top": [Vector2i(11, 8), Vector2i(15, 8), Vector2i(15, 9), Vector2i(15, 10), Vector2i(15, 11)],
		"bottom": [Vector2i(11, 9), Vector2i(11, 10), Vector2i(11, 11), Vector2i(11, 12), Vector2i(11, 15)],
		"shoes": [Vector2i(15, 13), Vector2i(15, 14), Vector2i(9, 13), Vector2i(9, 14)],
	},
	"chloe": {
		# hair = (11,12)/(11,13), face = (11,14)/(11,15), arms = col 15 rows 12-15
		"top": [Vector2i(5, 8), Vector2i(5, 11)],
		"bottom": [Vector2i(15, 9), Vector2i(15, 10), Vector2i(15, 8), Vector2i(15, 11), Vector2i(1, 13), Vector2i(1, 14)],
		"shoes": [Vector2i(9, 13), Vector2i(9, 14)],
	},
}

# ---------------------------------------------------------------------------
# Layer 2: outfits — garment recolors + gear loadout.
# An empty recolor dict means "wear the base model's own colors".
# ---------------------------------------------------------------------------
const OUTFITS: Dictionary = {
	"civvies": {"recolor": {}, "gear": []},
	"fatigues": {
		"recolor": {
			"top": COL_FATIGUE_TOP, "bottom": COL_FATIGUE_BOTTOM,
			"shoes": COL_FATIGUE_BOOT, "limbs": COL_FATIGUE_TOP,
			"accent": COL_FATIGUE_BOTTOM,
		},
		"gear": [],
	},
	"duty_black": {
		"recolor": {
			"top": COL_DUTY_TOP, "bottom": COL_DUTY_BOTTOM,
			"shoes": COL_DUTY_BOOT, "limbs": COL_DUTY_TOP,
		},
		"gear": ["sidearm"],
	},
	"combat": {
		"recolor": {
			"top": COL_FATIGUE_TOP, "bottom": COL_FATIGUE_BOTTOM,
			"shoes": COL_FATIGUE_BOOT, "limbs": COL_FATIGUE_TOP,
			"accent": COL_FATIGUE_BOTTOM,
		},
		"gear": ["sidearm", "rifle"],
	},
}

# ---------------------------------------------------------------------------
# Layer 1: who wears what where. Military crew: blacks + sidearm on the ship,
# camo + rifle + sidearm off-ship. Civilians: their own clothes on the ship,
# unarmed fatigues on missions.
# ---------------------------------------------------------------------------
const PROFILES: Dictionary = {
	"Eli": {"model": "eli", "ship": "civvies", "mission": "fatigues", "military": false},
	"Dr Rush": {"model": "rush", "ship": "civvies", "mission": "fatigues", "military": false},
	"Dr Park": {"model": "park", "ship": "civvies", "mission": "fatigues", "military": false},
	"Dr James": {"model": "james", "ship": "civvies", "mission": "fatigues", "military": false},
	"Chloe Armstrong": {"model": "chloe", "ship": "civvies", "mission": "fatigues", "military": false},
	"Lt Scott": {"model": "scott", "ship": "duty_black", "mission": "combat", "military": true},
	# Greer's skin/hair recolors bake into every outfit (the old away-team
	# hack tinted Scott's whole body brown; this is the parameterized version).
	"Sgt Greer": {
		"model": "greer", "ship": "duty_black", "mission": "combat", "military": true,
		"skin": Color(0.46, 0.28, 0.18), "hair": Color(0.10, 0.09, 0.08),
	},
	"Colonel Young": {"model": "young", "ship": "duty_black", "mission": "combat", "military": true},
	"Lt James": {"model": "lt_james", "ship": "duty_black", "mission": "combat", "military": true},
}

# Baked outfit textures, keyed "model|outfit". Characters sharing a look share
# one texture; recolors never touch the base colormap resource itself.
static var _texture_cache: Dictionary = {}


# --------------------------- profile resolution ----------------------------

static func profile_for(character_name: String) -> Dictionary:
	if PROFILES.has(character_name):
		return PROFILES[character_name]
	if ALIASES.has(character_name):
		return PROFILES[ALIASES[character_name]]
	# Generic spawn labels ("Soldier 2") fall back by keyword.
	if is_military(character_name):
		return {"model": "scott", "ship": "duty_black", "mission": "combat", "military": true}
	return {"model": "", "ship": "civvies", "mission": "fatigues", "military": false}


# Label variants resolve to the canonical profile so "Greer" (planet away
# team) and "Sgt Greer" (ship) are the same person.
const ALIASES: Dictionary = {
	"Greer": "Sgt Greer", "Scott": "Lt Scott", "Young": "Colonel Young",
	"Rush": "Dr Rush", "Park": "Dr Park", "Chloe": "Chloe Armstrong",
}


# Exact profile flag first; keyword fallback keeps every label variant a spawn
# site might use working ("Greer", "Soldier 2"). NOTE: "Dr James" is a civilian
# while "Lt James" is military — keyword matching alone can't tell them apart,
# which is why the profile flag wins.
static func is_military(character_name: String) -> bool:
	if PROFILES.has(character_name):
		return bool(PROFILES[character_name]["military"])
	return character_name.contains("Greer") \
		or character_name.contains("Scott") \
		or character_name.contains("Soldier")


# Resolve a character's base model path, falling back to a per-site default
# for characters not in the registry.
static func model_for(character_name: String, fallback: String = "") -> String:
	var stem: String = String(profile_for(character_name)["model"])
	if stem == "":
		return fallback
	return "res://models/characters/%s.glb" % stem


static func outfit_id_for(character_name: String, context: String) -> String:
	var profile: Dictionary = profile_for(character_name)
	return String(profile.get(context, "civvies"))


# ------------------------------- dressing ----------------------------------

# Dress a spawned character for a context: bake/apply the outfit texture onto
# the model and sync carried gear. `body` owns gear nodes (so they live in
# body space, independent of model scale); `model_root` is the Model holder
# wrapping the GLB instance. `model_scale` is the holder's scale — gear is
# calibrated for the room-standard 2.6 and scales proportionally elsewhere.
static func dress(body: Node3D, model_root: Node, character_name: String, context: String = CTX_SHIP, model_scale: float = 2.6) -> void:
	var outfit_id: String = outfit_id_for(character_name, context)
	apply_texture(model_root, character_texture(character_name, context))
	var outfit: Dictionary = OUTFITS.get(outfit_id, OUTFITS["civvies"])
	_sync_gear(body, outfit["gear"], model_scale)


# Walk the model and override every mesh with a material using `tex` — same
# idiom as Npc.apply_kenney_colormap (Godot drops the GLB's external texture
# binding on import; without this minis render solid white).
static func apply_texture(model_root: Node, tex: Texture2D) -> void:
	if model_root == null or tex == null:
		return
	var mat: StandardMaterial3D = StandardMaterial3D.new()
	mat.albedo_texture = tex
	mat.roughness = 0.78
	mat.metallic = 0.0
	var stack: Array = [model_root]
	while not stack.is_empty():
		var n: Node = stack.pop_back()
		if n is MeshInstance3D:
			(n as MeshInstance3D).material_override = mat
		for c in n.get_children():
			stack.append(c)


# ----------------------------- outfit baking -------------------------------

# The texture a specific character wears in a context: the outfit's recolors
# plus the profile's identity overrides (skin/hair) baked together. Greer's
# skin tone follows him into every outfit this way.
static func character_texture(character_name: String, context: String) -> Texture2D:
	var profile: Dictionary = profile_for(character_name)
	var stem: String = String(profile["model"])
	var outfit_id: String = outfit_id_for(character_name, context)
	if not (profile.has("skin") or profile.has("hair")):
		return outfit_texture(stem, outfit_id)
	var key: String = "%s|%s|%s" % [character_name, stem, outfit_id]
	if _texture_cache.has(key):
		return _texture_cache[key]
	var outfit: Dictionary = OUTFITS.get(outfit_id, OUTFITS["civvies"])
	var recolor: Dictionary = (outfit["recolor"] as Dictionary).duplicate()
	if profile.has("skin"):
		recolor["skin"] = profile["skin"]
	if profile.has("hair"):
		recolor["hair"] = profile["hair"]
	var baked: Texture2D = custom_texture(stem, recolor)
	_texture_cache[key] = baked
	return baked

# Bake (and cache) the colormap variant for a model+outfit. Civvies and
# unknown models return the base atlas untouched.
static func outfit_texture(model_stem: String, outfit_id: String) -> Texture2D:
	var key: String = "%s|%s" % [model_stem, outfit_id]
	if _texture_cache.has(key):
		return _texture_cache[key]
	var outfit: Dictionary = OUTFITS.get(outfit_id, OUTFITS["civvies"])
	var baked: Texture2D = custom_texture(model_stem, outfit["recolor"])
	_texture_cache[key] = baked
	return baked


# Uncached bake with an arbitrary recolor dict (role -> Color) — the Character
# Lab's live-tweak path. Promote a good result into OUTFITS to ship it.
static func custom_texture(model_stem: String, recolor: Dictionary) -> Texture2D:
	var base: Texture2D = load(COLORMAP_PATH)
	var groups: Dictionary = SWATCH_GROUPS.get(model_stem, {})
	if recolor.is_empty() or groups.is_empty():
		return base
	var img: Image = base.get_image()
	if img.is_compressed():
		img.decompress()
	img.convert(Image.FORMAT_RGBA8)
	for role in recolor:
		var target: Color = recolor[role]
		for cell in groups.get(role, []):
			_recolor_cell(img, cell, target)
	return ImageTexture.create_from_image(img)


# Luminance-preserving recolor of one 32px atlas cell: the swatch keeps its
# vertical gradient (Kenney's baked-in shading) but shifts to the target hue.
static func _recolor_cell(img: Image, cell: Vector2i, target: Color) -> void:
	var x0: int = cell.x * ATLAS_CELL
	var y0: int = cell.y * ATLAS_CELL
	if x0 < 0 or y0 < 0 or x0 + ATLAS_CELL > img.get_width() or y0 + ATLAS_CELL > img.get_height():
		return
	var mean_luma: float = 0.0
	for y in range(y0, y0 + ATLAS_CELL):
		for x in range(x0, x0 + ATLAS_CELL):
			var c: Color = img.get_pixel(x, y)
			mean_luma += (c.r + c.g + c.b) / 3.0
	mean_luma = maxf(mean_luma / float(ATLAS_CELL * ATLAS_CELL), 0.001)
	for y in range(y0, y0 + ATLAS_CELL):
		for x in range(x0, x0 + ATLAS_CELL):
			var c: Color = img.get_pixel(x, y)
			var f: float = ((c.r + c.g + c.b) / 3.0) / mean_luma
			img.set_pixel(x, y, Color(
				clampf(target.r * f, 0.0, 1.0),
				clampf(target.g * f, 0.0, 1.0),
				clampf(target.b * f, 0.0, 1.0),
				c.a))


# -------------------------------- gear -------------------------------------

# Make the body's gear match the outfit's loadout — removes gear that doesn't
# belong, adds what's missing. Extras like the standoff helmet are added
# explicitly via add_gear AFTER dressing.
static func _sync_gear(body: Node3D, loadout: Array, model_scale: float) -> void:
	for gear_name in ["Sidearm", "Rifle", "Helmet"]:
		var node: Node = body.get_node_or_null(gear_name)
		if node != null and not loadout.has(gear_name.to_lower()):
			node.queue_free()
			# Rename so get_node_or_null can't find the dying node this frame.
			node.name = gear_name + "_retired"
	for gear_id in loadout:
		add_gear(body, gear_id, model_scale)


# Idempotent: a body carries at most one of each gear kind.
static func add_gear(body: Node3D, gear_id: String, model_scale: float = 2.6) -> Node3D:
	var node_name: String = gear_id.capitalize()
	var existing: Node = body.get_node_or_null(node_name)
	if existing != null:
		return existing
	var gear: Node3D = null
	match gear_id:
		"sidearm":
			gear = build_sidearm()
		"rifle":
			gear = build_rifle()
		"helmet":
			gear = build_helmet()
	if gear == null:
		return null
	var k: float = model_scale / 2.6
	gear.position *= k
	gear.scale *= k
	body.add_child(gear)
	return gear


# Dark-olive combat helmet — a squashed dome on the crown. Standoff-only kit;
# never part of an outfit loadout.
static func build_helmet() -> MeshInstance3D:
	var helmet: MeshInstance3D = MeshInstance3D.new()
	helmet.name = "Helmet"
	var dome: SphereMesh = SphereMesh.new()
	dome.radius = 0.34
	dome.height = 0.46
	dome.is_hemisphere = true
	helmet.mesh = dome
	helmet.position = Vector3(0.0, 1.62, 0.0)
	var mat: StandardMaterial3D = StandardMaterial3D.new()
	mat.albedo_color = Color(0.20, 0.24, 0.16)
	mat.roughness = 0.7
	mat.metallic = 0.0
	helmet.material_override = mat
	return helmet


# Procedural sidearm on a pivot at the right hand. Starts barrel-down
# (holstered); the standoff raises it level on Greer's cue.
static func build_sidearm() -> Node3D:
	var pivot: Node3D = Node3D.new()
	pivot.name = "Sidearm"
	pivot.position = Vector3(0.40, 1.28, 0.30)
	pivot.rotation.x = -PI * 0.5
	var mat: StandardMaterial3D = StandardMaterial3D.new()
	mat.albedo_color = Color(0.05, 0.05, 0.06)
	mat.metallic = 0.6
	mat.roughness = 0.45
	var slide: MeshInstance3D = MeshInstance3D.new()
	var smesh: BoxMesh = BoxMesh.new()
	smesh.size = Vector3(0.11, 0.14, 0.54)
	slide.mesh = smesh
	slide.material_override = mat
	slide.position = Vector3(0.0, 0.0, -0.22)
	pivot.add_child(slide)
	var grip: MeshInstance3D = MeshInstance3D.new()
	var gmesh: BoxMesh = BoxMesh.new()
	gmesh.size = Vector3(0.08, 0.24, 0.11)
	grip.mesh = gmesh
	grip.material_override = mat
	grip.position = Vector3(0.0, -0.16, 0.06)
	pivot.add_child(grip)
	return pivot


# Kenney Blaster Kit rifle (blaster-e) on a pivot at low-ready across the
# chest, tinted gunmetal (the kit's toy colors don't read as military).
# Auto-scaled so the barrel spans ~0.85 body units regardless of source size.
static func build_rifle() -> Node3D:
	var pivot: Node3D = Node3D.new()
	pivot.name = "Rifle"
	# Minis are ~0.8 units deep at the chest — keep the carry position well in
	# front of the torso or the rifle embeds invisibly inside the mesh.
	pivot.position = Vector3(0.30, 1.15, 0.55)
	pivot.rotation.x = -0.28   # muzzle dipped — low ready
	pivot.rotation.y = -0.55   # carried diagonally across the body
	var glb: PackedScene = load(RIFLE_GLB)
	if glb == null:
		return pivot
	var inst: Node3D = glb.instantiate()
	var aabb: AABB = _merged_aabb(inst)
	var longest: float = maxf(aabb.size.x, maxf(aabb.size.y, aabb.size.z))
	if longest > 0.001:
		inst.scale = Vector3.ONE * (0.85 / longest)
	# Kenney blasters model the barrel along +Z; flip to -Z (body forward).
	if aabb.size.z >= aabb.size.x and aabb.size.z >= aabb.size.y:
		inst.rotation.y = PI
	else:
		inst.rotation.y = PI * 0.5
	# Center the mesh on the pivot.
	inst.position = -(aabb.get_center() * inst.scale).rotated(Vector3.UP, inst.rotation.y)
	var mat: StandardMaterial3D = StandardMaterial3D.new()
	mat.albedo_color = Color(0.24, 0.25, 0.28)
	mat.metallic = 0.45
	mat.roughness = 0.45
	var stack: Array = [inst]
	while not stack.is_empty():
		var n: Node = stack.pop_back()
		if n is MeshInstance3D:
			(n as MeshInstance3D).material_override = mat
		for c in n.get_children():
			stack.append(c)
	pivot.add_child(inst)
	return pivot


# Transform-aware merged AABB in `root`'s local frame. MeshInstance3D.get_aabb()
# alone is mesh-local and misses inner node scales (Kenney blasters nest a
# scaled node inside the GLB), which made the rifle measure 3x its true size.
static func _merged_aabb(root: Node) -> AABB:
	var merged: AABB = AABB()
	var first: bool = true
	if root is MeshInstance3D:
		merged = (root as MeshInstance3D).get_aabb()
		first = false
	for c in root.get_children():
		var out: Array = _aabb_walk(c, Transform3D.IDENTITY, merged, first)
		first = out[0]
		merged = out[1]
	return merged


static func _aabb_walk(node: Node, xf: Transform3D, merged: AABB, first: bool) -> Array:
	var local_xf: Transform3D = xf
	if node is Node3D:
		local_xf = xf * (node as Node3D).transform
	if node is MeshInstance3D:
		var box: AABB = local_xf * (node as MeshInstance3D).get_aabb()
		if first:
			merged = box
			first = false
		else:
			merged = merged.merge(box)
	for c in node.get_children():
		var out: Array = _aabb_walk(c, local_xf, merged, first)
		merged = out[1]
		first = out[0]
	return [first, merged]
